apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  labels:
    name: app
spec:
  project: default
  source:
    repoURL: https://github.com/jsaulalonso/gitops.git
    targetRevision: main
    path: app
    helm:
      valueFiles:
        - values/pro.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: bigbang
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
